kind: pipeline
name: 正式版

steps: 
   #git镜像
 - name: tlf
   image: alpine/git
   commands:
   - git checkout origin/tlf -B tlf

 - name: notify #   3. 通知（这里使用了钉钉通知，可以使用微信通知、邮件通知等）
   pull: if-not-exists
   image: guoxudongdocker/drone-dingtalk:latest
   settings:
      token:
        from_secret: dingtalk_token
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
   when:
      status: [failure, success]

volumes:        #定义流水线挂载目录
- name: docker
  host:
    path: /var/run/docker.sock

trigger:       #管道执行触发条件
  branch:
  - tlf